dataset:
  name: "imagenet"
  num_classes: 1000
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  image_size: [224, 224]

models:
  use_torchvision: True

paths:
  # Using "." assumes you run from the root where data/ folder is located
  train_data: "data/images_largescale"
  train_list: "data/benchmark_imglist/imagenet/train_imagenet.txt"

  val_data: "data/images_largescale"
  val_list: "data/benchmark_imglist/imagenet/val_imagenet.txt"

  out_dir: "data/images_largescale/imagenet_ln_final_v2"
  ae_weights: "ln_dataset/assets/imagenet_ae/model.pth"

calibration:
  target_fracs: [0.35, 0.25, 0.20, 0.15, 0.05]